language: node_js
node_js:
  - "10"
stages:
- name: test
- name: staging
  if: branch = master AND type = push
- name: pr-staging
  if: type = pull_request
- name: production
  if: tag IS present

dist: xenial
jobs:
  include:
  - stage: test
    language: node_js
    node_js: "10"
